language: r
os: linux
dist: focal
r: release
pandoc_version: 2.9.2

branches:
  only:
    - dev
    - master

cache:
  packages: true
  directories:
    - $HOME/bin

script:
  - Rscript -e "qcbsRworkshops::build_workshops(update_template = TRUE, pdf = TRUE, script = TRUE)"

before_deploy:
  - mkdir public
  - cp README.md public
  - cp -r workshop* public/

deploy:
  provider: pages
  token: $GH_TOKEN
  strategy: git 
  skip_cleanup: true
  keep_history: false
  target_branch: master
  local_dir: public
  on:
    branch: dev