# (PART\*) Unconstrained Ordination {-}

# What does "unconstrained" mean?

Unconstrained ordination allows us to organize samples, sites or species
along continuous gradients (e.g. ecological or environmental). The key
difference between unconstrained and constrained ordination (discussed
later in this workshop- see 'Canonical Ordination') is that in the
unconstrained techniques we are not attempting to define a relationship
between independent and dependent sets of variables.

Unconstrained ordination can be used to: 

- Assess relationships *within*
a set of variables (not between sets). 
- Find key components of
variation between samples, sites, species etc. 
- Reduce the number
dimensions in multivariate data without substantial loss of information.
- Create new variables for use in subsequent analyses (such as
regression). These principal components are weighted, linear
combinations of the original variables in the ordination.

[Source](http://www.umass.edu/landeco/teaching/multivariate/schedule/ordination1.pdf)