# (PART\*) Modèles linéaires mixtes en `R` {-}

# Objectifs d'apprentissage

**Résumé:** Les modèles à effets mixtes permettent aux écologistes de
surmonter un certain nombre de limitations liées aux modèles linéaires
traditionnels. Dans cet atelier, vous apprendrez à déterminer si vous
devez utiliser un modèle à effets mixtes pour analyser vos données. Nous
allons vous guider à travers les étapes nécessaires pour utiliser un
modèle linéaire mixte, vérifier les suppositions de base et présenter
les résultats de votre modèle dans R. Nous allons également nous baser
sur ce qui a été appris durant le dernier cours afin d'introduire les
modèles linéaires généralisés avec effets mixtes.

**Objectifs d'apprentissage**

-    Qu'est-ce qu'un modèle linéaire à effets mixtes (MLM) et pourquoi est-ce important?
-    Comment appliquer des MLMs dans R?
      - Construction et exploration a priori des modèles et données
      - Codage et sélection des modèles potentiels 
      - Validation des modèles
      - Interprétation des résultats et visualisation du modèle
-   Comment utiliser les MLM quand les suppositions de normailité et d'homogénéité de la variance ne sont pas respectées (GLMMs).
.

# Préparez-vous pour cet atelier

**Téléchargez le script R et les données pour cet atelier:**

-    [R Script](http://qcbs.ca/wiki/_media/lmm_e.r)
-    [Fish data](http://qcbs.ca/wiki/_media/qcbs_w6_data.csv)
-    [Arabidopsis data](http://qcbs.ca/wiki/_media/banta_totalfruits.csv)
-    [Inverts data](http://qcbs.ca/wiki/_media/inverts.csv)
-    [GLMM Script](http://qcbs.ca/wiki/_media/glmm_e.r) 
-    [glmm_funs](http://qcbs.ca/wiki/_media/glmm_funs.r) 

**Télechargez les paquets R pour cet atelier:**

-    [ggplot2](http://cran.r-project.org/web/packages/ggplot2/index.html)
-    [lm4](http://cran.r-project.org/web/packages/lme4/index.html)
-    [AICcmodavg](http://cran.r-project.org/web/packages/AICcmodavg/index.html)
-    [MASS](http://cran.r-project.org/web/packages/MASS/index.html)
-    [vcdExtra](http://cran.r-project.org/web/packages/vcdExtra/index.html)
-    [bbmle](http://cran.r-project.org/web/packages/bbmle/index.html)
-    [DescTools](http://cran.r-project.org/web/packages/DescTools/index.html)


```{r, echo = TRUE, eval = FALSE}
install.packages("ggplot2")
install.packages("lme4")
install.packages("AICcmodavg")
install.packages("MASS")
install.packages("vcdExtra")
install.packages("bbmle")
install.packages("DescTools")

library(ggplot2)
library(lme4)
library(AICcmodavg)
library(MASS)
library(vcdExtra)
library(bbmle)
library(DescTools)
```
